export const films = [
    {
        id: "The_Walking_Dead",
        titre: "The Walking Dead",
        annee_de_sortie: "2010-2022",
        descriotion: "le shérif adjoint Rick Grimes sort du coma et apprend que le monde est en ruine, il doit aider un groupe de survivants à rester en vie.",
        auteur: "Robert kirkman",
        niveau_de_difficulter: "Evident",
        points: "5",
    },
    {
        id: "L'Attaque_des_Titans",
        titre:"L'Attaque des Titans",
        annee_de_sortie: "2013-2023",
        descriotion: "Après la destruction de sa ville natale et la mort de sa mère, le jeune Eren Yeager promet de purger la terre des géants humanoïdes appelés Titans qui menacent l'humanité toute entière.",
        auteur: "Shinji Higuchi",
        niveau_de_difficulter: "Facile",
        points: "10",  
    },
    {
        id: "La_Planète des_Singes",
        titre: "La Planète des Singes",
        annee_de_sortie: "2001",
        descriotion: "En 2029, un astronaute de la Force aérienne se heurte à une planète énigmatique où des singes évolués et parlants dominent une race d'humains primitifs.",
        auteur: "Pierre Boulle",
        niveau_de_difficulter: "Difficile",
        points: "20", 
    },
    {
        id: "Je_suis_une_légende",
        titre: "Je suis une légende",
        annee_de_sortie: "2007",
        descriotion: "Des années après qu'une épidémie a anéanti presque tous les êtres humains et transformé le reste en monstres, le seul survivant à New York se bat vaillamment pour trouver un remède.",
        auteur: "Richard Matheson",
        niveau_de_difficulter: "Moyen",
        points: "15",
    },
    {
        id: "The_Road",
        titre: "The Road",
        annee_de_sortie: "2014-2015",
        descriotion: "Un policier local essaie de faire face aux problèmes au sein de sa famille tandis que la tension croissante dans la communauté entraîne une effusion de sang.",
        auteur: "Cormac McCarthy",
        niveau_de_difficulter: "Evident",
        points: "5",
    },
    {
        id: "Snowpiercer",
        titre: "Snowpiecer",
        annee_de_sortie: "2013",
        descriotion: "Dans un futur où une expérience de changement climatique ratée a tué toute vie sur Terre, à l'exception de quelques chanceux qui ont embarqué dans le Snowpiercer, le transperceneige, un train où a surgi une hiérarchie des classes et qui voyage autour du globe.",
        auteur: "Bong Joon-ho",
        niveau_de_difficulter: "Moyen",
        points: "15",
    },
{
        id: " World_war_Z",
        titre : " World war Z",
        annee_de_sortie: "2013",
        descriotion: "Gerry Lane, ancien employé des Nations Unies, traverse le monde dans une véritable course contre la montre pour mettre fin à la pandémie de zombies qui renverse les armées et les gouvernements et menace de détruire l'humanité toute entière.",
        auteur: "Marc Forster",
        niveau_de_difficulter: "Evident",
        points: "5",
},
{
        id: "The_Last_of_Us",
        titre: "The Last of Us",
        annee_de_sortie: "2023",
        descriotion: "20 ans après une pandémie transformant les humains en zombies, un homme ayant perdu sa fille à l'aube de cette pandémie ainsi qu'une orpheline ayant croisé sa route vont se lancer dans un voyage afin de rejoindre d'autres survivants",
        auteur: "Neil Druckmann",
        niveau_de_difficulter: "Moyen",
        points: "15",
},
{
        id: "Akira",
        titre: "Akira",
        annee_de_sortie: "1988",
        descriotion: "Un projet militaire secret met en danger Néo-Tokyo lorsqu'il transforme le membre d'un gang de motards en un psychopathe psychique déchaîné qui ne peut être arrêté que par deux adolescents et un groupe de voyants.",
        auteur: "Katsuhiro Ōtomo",
        niveau_de_difficulter: "Evident",
        points: "5",
},
{
        id: "Dr_Stone",
        titre: "Dr.Stone",
        annee_de_sortie: "2019",
        descriotion: "Dans un monde où l'humanité a été pétrifiée, le génie scientifique Senku et son ami musclé Taiju utilisent leurs compétences pour reconstruire la civilisation.",
        auteur: "Riichiro Inagak",
        niveau_de_difficulter: "Moyen",
        points: "15",
},
{
        id: " Fallout",
        titre: " Fallout",
        annee_de_sortie: "2024",
        descriotion: "Adaptation du jeu vidéo se déroulant dans une Amérique post apocalyptique.",
        auteur: "Jonathan Nolan",
        niveau_de_difficulter: "Difficile",
        points: "20",
},
{
        id: "  Bird_Box",
        titre: "  Bird Box",
        annee_de_sortie: "2018",
        descriotion: "Une femme et deux enfants aux yeux bandés traversent un endroit dystopique au bord d'une rivière.",
        auteur: "Susanne Bier",
        niveau_de_difficulter: "Facile",
        points: "10",
},
{
        id: "A_Quiet_Place",
        titre: "A Quiet Place",
        annee_de_sortie: "2018",
        descriotion: "Dans un monde post-apocalyptique, une famille est forcée de vivre en silence pour se protéger de monstres à l'ouïe ultra-sensible.",
        auteur: "John Krasinski",
        niveau_de_difficulter: "Evident",
        points: "5",
},
{
        id: "Waterworld",
        titre: "Waterworld",
        annee_de_sortie: "1995",
        descriotion: "Alors que les calottes glaciaires ont fondu et que la Terre est presque entièrement submergée, un marin qui a subi une mutation décide de combattre la famine et d'interdire les.", 
        niveau_de_difficulter: "Difficile",
        points: "20",
},
{
        id: "The_Book_of_Eli",
        titre: "The Book of Eli",
        annee_de_sortie: "2010",
        descriotion: "Un conte post-apocalyptique dans lequel un homme solitaire se bat à travers l'Amérique pour protéger un livre sacré qui détient les secrets de la sauvegarde de l'humanité",
        auteur: "Albert Hughes",
        niveau_de_difficulter: "Evident",
        points: "5",
},
{
        id: "The_Maze_Runner",
        titre: "The Maze Runner",
        annee_de_sortie: "2014",
        descriotion: "Thomas est déposé dans une communauté de garçons après que sa mémoire a été effacée et découvre bientôt qu'ils sont tous pris au piège dans un labyrinthe. Il va devoir unir ses forces à celles de ces compagnons ",
        auteur: "Wes Ball",
        niveau_de_difficulter: "Facile",
        points: "10",
},
{
        id: "Station_Eleven",
        titre: "Station Eleven",
        annee_de_sortie: "2021",
        descriotion: "Vingt ans après qu'une grippe dévastatrice a effondré la civilisation, une troupe d'acteurs nomades tente de maintenir la culture vivante tout en affrontant un culte mystérieux. Une œuvre post-apocalyptique lumineuse qui explore l'importance de l'art pour la survie de l'humanité.",
        auteur: "Patrick Somerville",
        niveau_de_difficulter: "Evident",
        points: "5",
},
{
        id: "12_Monkeys",
        titre: "12 Monkeys",
        annee_de_sortie: "1995",
        descriotion: "En 2035, un prisonnier est envoyé dans le passé pour identifier l'origine d'un virus mortel ayant décimé l'humanité. Entre asile psychiatrique et paradoxes temporels, il tente de remonter la piste de l'armée des 12 singes.",
        auteur: "Terry Gilliam",
        niveau_de_difficulter: "Moyen",
        points: "15",
},
{
        id: "Interstellar",
        titre: "Interstellar",
        annee_de_sortie: "2014",
        descriotion: "Alors que la Terre se meurt, un groupe d'astronautes franchit un trou de ver pour trouver une nouvelle planète habitable. Un voyage spatial épique qui explore les limites de la physique, du temps et de l'amour paternel.",
        auteur: "Christopher Nolan",
        niveau_de_difficulter: "Facile",
        points: "10",
},
{
        id: "Gurren_Lagann",
        titre:"Gurren Lagann",
        annee_de_sortie: "2008",
        descriotion: "Dans un futur où l'humanité est forcée de vivre sous terre, le jeune Simon découvre un petit robot qui lui permettra, aux côtés du flamboyant Kamina, de percer la surface pour défier le destin de l'univers",
        auteur: "Hiroyuki Imaishi",
        niveau_de_difficulter: "Difficile",
        points: "20",
},
{
        id: "The Matrix",
        titre:"The Matrix",
        annee_de_sortie: "",
        descriotion: "Un programmeur découvre que sa réalité n'est qu'une simulation informatique créée par des machines pour asservir l'humanité. Il rejoint alors une rébellion pour briser ses chaînes numériques et devenir l'Élu",
        auteur: "Les Wachowski",
        niveau_de_difficulter: "Moyen",
        points: "15",
},
{
        id: "Terminator_2_judgment Day",
        titre:"Terminator 2 judgment Day",
        descriotion: "n nouveau Terminator en métal liquide, plus avancé, est envoyé pour éliminer le jeune John Connor. Pour le protéger, la résistance renvoie un T-800 reprogrammé, déclenchant une course-poursuite explosive pour empêcher l'apocalypse",
        auteur: "1991",
        niveau_de_difficulter: "Facile",
        points: "5",
},
{
        id: "Resident_Evil",
        titre:"Resident Evil",
        annee_de_sortie: "2002",
        descriotion: "Dans un laboratoire souterrain secret, un virus mortel s'échappe et transforme le personnel en zombies assoiffés de sang. Une unité d'élite doit infiltrer le complexe pour désactiver l'IA devenue incontrôlable et contenir l'épidémie.",
        auteur: "Paul W.S. Anderson",
        niveau_de_difficulter: "Difficile",
        points: "20",
},
{
        id: "Deep Impact",
        titre:"Deep Impact",
        annee_de_sortie: "1998",
        descriotion: "Un jeune astronome découvre qu'une comète géante est sur une trajectoire de collision directe avec la Terre. Alors qu'une mission spatiale tente de la détruire, l'humanité se prépare au choc inévitable et à une possible extinction.",
        auteur: "Mimi Leder",
        niveau_de_difficulter: "Difficile",
        points: "20",
},
{
        id: "28 Days Later",
        titre:"28 Days Later",
        annee_de_sortie: "2002",
        descriotion: "Un homme se réveille d'un coma dans un Londres désert, 28 jours après la propagation d'un virus de la . Il doit s'allier à d'autres survivants pour échapper aux infectés et trouver un refuge militaire qui s'avère tout aussi dangereux",
        auteur: "Danny Boyle",
        niveau_de_difficulter: "Evident",
        points: "5",
},
{
        id: "Mad_Max_Fury_Road",
        titre:"Mad Max: Fury Road",
        annee_de_sortie: "2015",
        descriotion: "Dans un désert post-apocalyptique, Max s'allie à l'Impératrice Furiosa pour fuir un tyran et ses armées dans une course-poursuite infernale. Ensemble, ils tentent de traverser le désert à bord d'un camion-citerne pour atteindre une terre promise.",
        auteur: "George Miller",
        niveau_de_difficulter: "Moyen",
        points: "15",
},
{
        id: "Dawn of the Dead",
        titre:"Dawn of the Dead",
        annee_de_sortie: "1978",
        descriotion: "Alors qu'une épidémie de morts-vivants ravage les États-Unis, quatre survivants se barricadent dans un centre commercial. Ils tentent d'y recréer une vie normale tout en luttant contre les rôdeurs et une bande de pillards.",
        auteur: "George A. Romero",
        niveau_de_difficulter: "Facile",
        points: "5",
},
{
        id: "Edge_of_Tomorrow",
        titre:"Edge of Tomorrow",
        annee_de_sortie: "2014",
        descriotion: "Un officier sans expérience de combat se retrouve coincé dans une boucle temporelle lors d'une invasion extraterrestre, revivant sans cesse la même bataille. À chaque mort, il devient plus fort et cherche avec une soldate d'élite le moyen de vaincre l'ennemi.",
        auteur: "Doug Liman",
        niveau_de_difficulter: "Moyenn",
        points: "15",
},
{
        id: "2012",
        titre:"2012",
        annee_de_sortie: "2009",
        descriotion: "Un chercheur découvre que le noyau de la Terre surchauffe, provoquant des séismes et des tsunamis qui menacent de rayer l'humanité de la carte. Un père de famille tente désespérément de sauver les siens alors que le monde s'écroule littéralement autour d'eux.",
        auteur: "Roland Emmerich",
        niveau_de_difficulter: "Evident",
        points: "5",
}
];

export function getFilmById(id) {
  return films.find(f => f.id === id);
}

export function checkAnswer(id, reponse) {
  const film = getFilmById(id);
  return film.title.toLowerCase() === reponse.toLowerCase();
}
